// Đăng xuất
GET http://localhost:5000/auth/logout

###
// Đăng nhập bằng mã nhân viên  (Thủ thư)
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "TT0001",
  "password":"12345678"
}
###
// Đăng nhập bằng mã nhân viên  (Quản kho)
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "QK0001",
  "password":"12345678"
}
###
// Đăng nhập bằng mã nhân viên  (Quản trị viên)
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "QT0001",
  "password":"12345678"
}

###
// Đăng nhập bằng email đọc giả
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "tranhuynhchuong00@gmail.com",
  "password":"12345678"
}

###
// Đăng ký tài khoản độc giả
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "tranhuynhchuong00@gmail.com",
    "password": "12345678",
    "password2": "12345678",
    "MaDocGia" : "DG002",
    "HoLot" : "Trần Huỳnh",
    "Ten" : "Chương",
    "NgaySinh" : "2003-03-05",
    "Phai" : "Nam",
    "DiaChi" : "Việt Nam",
    "SoDienThoai" : "0702922401"

}
