

###// Hiển thị tất cả sách
GET http://localhost:5000/books

###//Hiển thị chi tiết sách (id)
GET http://localhost:5000/staff/manage-books/66cc674d5766472d43afda63

###//Tìm kiếm sách bằng từ khóa
GET http://localhost:5000/books/search?keyword=CT113